// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE52z13tufN-HvnXhrRaulA2BE548pS7M',
    appId: '1:259369139585:android:e5d9b776f4c91ebe373c80',
    messagingSenderId: '259369139585',
    projectId: 'swit-91d08',
    databaseURL: 'https://swit-91d08-default-rtdb.firebaseio.com',
    storageBucket: 'swit-91d08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUp9838fbRTLyMcbctY50UapcaPYq6P1c',
    appId: '1:259369139585:ios:e89218e72df8e0c9373c80',
    messagingSenderId: '259369139585',
    projectId: 'swit-91d08',
    databaseURL: 'https://swit-91d08-default-rtdb.firebaseio.com',
    storageBucket: 'swit-91d08.appspot.com',
    androidClientId: '259369139585-ne1kmi14l6m582m0om23d00nulb659lp.apps.googleusercontent.com',
    iosClientId: '259369139585-465gq5i390ndt8sedrckefo34l6sevmb.apps.googleusercontent.com',
    iosBundleId: 'com.swit91d08.swit',
  );
}
